services:
  - type: web
    name: vaaniai-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py server:app
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: vaaniai_production
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: vaaniai-frontend
    env: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: vaaniai-backend
          property: host
      - key: NODE_VERSION
        value: 20.15.0